# Generated by Django 4.0.10 on 2024-04-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress_camping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Adresse_complète', models.CharField(max_length=200)),
                ('Pays', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camping_name', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('camping_city', models.CharField(max_length=200)),
                ('camping_country', models.CharField(max_length=200)),
                ('emission_total', models.CharField(max_length=200)),
                ('Adress_camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping', to='camping.adress_camping')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_adress', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=200)),
                ('client_city', models.CharField(max_length=200)),
                ('client_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions', models.FloatField()),
                ('vehicule', models.CharField(choices=[('Combustion engine car', 'Combustion engine car'), ('Electric engine car', 'Electric engine car'), ('Train', 'Train'), ('Bus', 'Bus')], default='voiture', max_length=200)),
                ('distance', models.FloatField()),
                ('year', models.IntegerField()),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.camping')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.client')),
            ],
        ),
    ]
