# Generated by Django 5.0.4 on 2024-05-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse_camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adresse_complète', models.CharField(max_length=200)),
                ('Pays', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_city', models.CharField(max_length=200)),
                ('client_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], default='US', max_length=2)),
                ('administrateur', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camping_name', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('camping_city', models.CharField(max_length=200)),
                ('camping_country', models.CharField(max_length=200)),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping', to='camping.adresse_camping')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions', models.FloatField(default=None, null=True)),
                ('vehicle', models.CharField(choices=[('Combustion engine car', 'Combustion engine car'), ('Electric engine car', 'Electric engine car'), ('Train', 'Train'), ('Bus', 'Bus')], default='voiture', max_length=200)),
                ('distance', models.FloatField(default=None, null=True)),
                ('year', models.IntegerField()),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.camping')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.client')),
            ],
        ),
    ]
