# Generated by Django 4.0.10 on 2024-04-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camping',
            old_name='Adress_camping',
            new_name='id_adresse',
        ),
    ]
