# Generated by Django 5.0.6 on 2024-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_alter_login_managers_login_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('MG', 'Manager général'), ('GC', 'Gestionnaire de camping')], default='GC', max_length=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.CharField(choices=[('Combustion engine car', 'Combustion engine car'), ('Electric engine car', 'Electric engine car'), ('Train', 'Train'), ('Bus', 'Bus')], default='Combustion engine car', max_length=200),
        ),
    ]
