# Generated by Django 4.0.10 on 2024-04-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_rename_adress_camping_camping_id_adresse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress_camping',
            new_name='Adresse_camping',
        ),
    ]
